---
title: "Lab 00 - Hello IDS!"
author: "hannahmca03"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse)

```

### Exercises 16-17

We set up the data frame. Edit the data below to include information about your team members.

```{r setup-tibble}
team_data <- tibble(
  name = c("Hannah", "Niamh", "Ãine", 
           "Shea", "Megan"),
  github_username = c("hannahmca03", "doc", "bobin", 
                      "hamsterboy", "tapshoes"), 
  colour = c("skyblue", "yellow", "mediumorchid3", 
             "springgreen2", "lightpink"),
  hobby = c("reading", "bouldering", "pottery", 
            "kayaking", "baking"),
  favourite_number = c(7, 5, 3, 10, 8)
  )

team_data
```

### Exercise 18

We now work on visualising our data. 

```{r bar-plot}
p1 <- ggplot(data = team_data, 
             mapping = aes(x = github_username, 
                           y = favourite_number,
                           fill = colour), 
             ) +
   geom_col() +
   scale_fill_identity()
p1
```

The favourite colour of each person

### Exercises 19

Change the text of the plot title and axis labels.

```{r labelled-bar-plot}
p1 + labs(x = "github username", 
          y = "favourite number",
          title = "favourite number of each user")
```

bar chart showing the fqvourite number of each user

### Exercise 20

```{r new-bar-plot}
p2 <- ggplot(team_data, aes(x = hobby)) +
  geom_bar()
p2
```

display using a table
